export const START = "START";
export const NEXT_STEP = "NEXT_STEP";
export const EDIT_TODO = "EDIT_TODO";
export const UPDATE_NUMBER_OF_TYPES = "UPDATE_NUMBER_OF_TYPES";
export const UPDATE_NUMBER_OF_TILES = "UPDATE_NUMBER_OF_TILES";
